{{/* Airflow environment variables */}}
{{- define "airflow_environment" }}
  # Dynamically created environment variables
  {{- range $i, $config := .Values.env }}
  - name: {{ $config.name }}
    value: {{ $config.value | quote }}
  {{- end }}
  # Hard Coded Airflow Envs
  - name: AIRFLOW__CORE__EXECUTOR
    value: "CeleryExecutor"
  - name: AIRFLOW__SCHEDULER__STATSD_ON
    value: "True"
  - name: AIRFLOW__SCHEDULER__STATSD_PORT
    value: "9125"
  - name: AIRFLOW__SCHEDULER__STATSD_PREFIX
    value: "airflow"
  - name: ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION
    value: "15"
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value:{{- include "airflow_url" . }}

  # Dynamically created secret envs
  {{- range $i, $config := .Values.secret }}
  - name: {{ $config.name }}
    valueFrom:
      secretKeyRef:
        name: {{ $config.value }}
        key:  value
  {{- end}}
  # Hard Coded Secret Envs
  - name: AIRFLOW__SCHEDULER__STATSD_HOST
    value: "{{ .Release.Name }}-statsd"
  - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    valueFrom:
      secretKeyRef:
        name: {{ .Values.data.airflowMetadataSecret }}
        key: connection
  - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
    valueFrom:
      secretKeyRef:
        name: {{ .Values.data.airflowResultBackendSecret }}
        key: connection
  - name: AIRFLOW__CELERY__BROKER_URL
    valueFrom:
      secretKeyRef:
        name: {{ .Values.data.airflowBrokerSecret }}
        key: connection
{{- end }}

# On the same line due to whitespace issue
{{ define "airflow_url" }} airflow.{{ .Values.global.baseDomain }}
{{- end }}
