{{/* Airflow environment variables */}}
{{- define "airflow_environment" }}
  # Dynamically created environment variables
  {{- range $i, $config := .Values.env }}
  - name: {{ $config.name }}
    value: {{ $config.value | quote }}
  {{- end }}
  # Hard Coded Airflow Envs
  - name: AIRFLOW__CORE__EXECUTOR
    value: "CeleryExecutor"
    name: AIRFLOW__CELERY__DEFAULT_QUEUE
    value: "celery"
  - name: AIRFLOW__SCHEDULER__STATSD_ON
    value: "True"
  - name: AIRFLOW__SCHEDULER__STATSD_PORT
    value: "9125"
  - name: AIRFLOW__SCHEDULER__STATSD_PREFIX
    value: "airflow"
  - name: ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION
    value: "15"
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: {{- include "airflow_url" . | indent 1 }}
  # Dynamically created secret envs
  {{- range $i, $config := .Values.secret }}
  - name: {{ $config.name }}
    valueFrom:
      secretKeyRef:
        name: {{ $config.value }}
        key:  value
  {{- end}}
  # Hard Coded Secret Envs
  - name: AIRFLOW__SCHEDULER__STATSD_HOST
    value: "{{ .Release.Name }}-statsd"
  - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    valueFrom:
      secretKeyRef:
        name: {{ .Values.data.airflowMetadataSecret }}
        key: connection
  - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
    valueFrom:
      secretKeyRef:
        name: {{ .Values.data.airflowResultBackendSecret }}
        key: connection
  - name: AIRFLOW__CELERY__BROKER_URL
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-celery-backend-uri
        key: connection
  - name: AIRFLOW__CORE__FERNET_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-fernet-key
        key: fernet-key
{{- end }}

{{ define "airflow_url" -}}
{{ .Release.Name }}-airflow.{{ .Values.global.baseDomain }}
{{- end }}

{{ define "flower_url" -}}
{{ .Release.Name }}-flower.{{ .Values.global.baseDomain }}
{{- end }}

{{ define "fernet_key" -}}
{{ (randAlphaNum 32 | b64enc) | b64enc }}
{{- end }}



{{ define "celery_backend_uri" -}}
{{ $redis_password := randAlphaNum 10 | b64enc | quote }}
redis://:{{ $redis_password }}@{{ .Release.Name }}-redis:6379/0
{{- end }}

{{ define "airflow_image" -}}
{{ .Values.images.airflow.name }}:{{ or .Values.global.imageTag .Values.images.airflow.tag }}
{{- end }}

{{ define "statsd_image" -}}
{{ .Values.images.statsd.name }}:{{ or .Values.global.imageTag .Values.images.statsd.tag }}
{{- end }}

{{ define "redis_image" -}}
{{ .Values.images.redis.name }}:{{ or .Values.global.imageTag .Values.images.redis.tag }}
{{- end }}
