################################
## Airflow Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-airflow-ingress
  labels:
    tier: airflow-networking
    component: airflow-ingress
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
    nginx.ingress.kubernetes.io/auth-url: https://houston.{{ .Values.global.baseDomain }}/authorization
    nginx.ingress.kubernetes.io/auth-signin: https://app.{{ .Values.global.baseDomain }}/login
    nginx.ingress.kubernetes.io/auth-response-headers: authorization, username, email

spec:
  {{- if or .Values.global.tlsSecret .Values.global.acme }}
  tls:
  {{- if .Values.global.acme }}
    - secretName: {{ .Release.Name }}-airflow-tls
  {{- end }}
  {{- if .Values.global.tlsSecret }}
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - {{- include "airflow_url" . | indent 1 }}
        - {{- include "flower_url" . | indent 1 }}
  {{- end }}
  rules:
    - host: {{- include "airflow_url" . | indent 1 }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-webserver
              servicePort: webserver-ui
    - host: {{- include "flower_url" . | indent 1 }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-flower
              servicePort: flower-ui
{{- end }}
