################################
## Airflow Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-airflow-ingress
  labels:
    tier: airflow-networking
    component: airflow-ingress
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
    {{- if .Values.global.nginxAuthSecret }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: {{ .Values.global.nginxAuthSecret }}
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
spec:
  {{- if or .Values.global.tlsSecret .Values.global.acme }}
  tls:
  {{- if .Values.global.acme }}
    - secretName: airflow-tls
  {{- end }}
  {{- if .Values.global.tlsSecret }}
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - {{ .Release.Name }}-airflow.{{ .Values.global.baseDomain }}
        - {{ .Release.Name }}-flower.{{ .Values.global.baseDomain }}
        - {{ .Release.Name }}-grafana.{{ .Values.global.baseDomain }}
        - {{ .Release.Name }}-prometheus.{{ .Values.global.baseDomain }}
  {{- end }}
  rules:
    - host: {{ .Release.Name }}-airflow.{{ .Values.global.baseDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-webserver
              servicePort: webserver-ui
    - host: {{ .Release.Name }}-flower.{{ .Values.global.baseDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-flower
              servicePort: flower-ui
    - host: {{ .Release.Name }}-grafana.{{ .Values.global.baseDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-grafana
              servicePort: grafana-ui
    - host: {{ .Release.Name }}-prometheus.{{ .Values.global.baseDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-prometheus
              servicePort: prometheus-data
{{- end }}
