################################
## Airflow Namespace LimitRange
#################################
{{- if .Values.limits }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limit-range
spec:
  limits:
{{ toYaml .Values.limits | indent 4 }}
{{- end }}
