################################
## Airflow Namespace
#################################
{{- if .Values.platform.namespace }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ include "namespace" . }}
  labels:
    tier: deployment
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
{{- end }}
