################################
## Airflow Namespace ResourceQuota
#################################
{{- if .Values.quotas }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-resource-quota
spec:
  hard:
{{ toYaml .Values.quotas | indent 4 }}
{{- end }}
