################################
## Astronomer Airflow Secrets
#################################
{{- define "metadataConnectionString" }}
  {{- with .Values.data.metadata }}
    {{- printf "postgresql://%v:%v@%v:%v/%v" .username .password .host .port .database | b64enc }}
  {{- end }}
{{- end }}

{{- define "resultsConnectionString" }}
  {{- with .Values.data.results }}
    {{- printf "db+postgresql://%v:%v@%v:%v/%v" .username .password .host .port .database | b64enc }}
  {{- end }}
{{- end }}

{{- define "brokerConnectionString" }}
  {{- with .Values.data.broker }}
    {{- printf "redis://%v:%v@%v:%v/%v" .username .password .host .port .database | b64enc }}
  {{- end }}
{{- end }}

{{- define "grafanaConnectionString" }}
  {{- with .Values.data.grafana }}
    {{- printf "postgres://%v:%v@%v:%v/%v" .username .password .host .port .database | b64enc }}
  {{- end }}
{{- end }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-metadata
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
type: Opaque
data:
  connection: {{ template "metadataConnectionString" . }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-results
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
type: Opaque
data:
  connection: {{ template "resultsConnectionString" . }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-broker
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
type: Opaque
data:
  connection: {{ template "brokerConnectionString" . }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-grafana
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
type: Opaque
data:
  connection: {{ template "grafanaConnectionString" . }}
