################################
## Airflow Secrets
#################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fernet-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  fernet-key: {{ template "fernet_key" . }}
