{{ $redis_password := randAlphaNum 10 }}
################################
## Airflow Secrets
#################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fernet-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  fernet-key: {{ template "fernet_key" . }}

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-redis-password
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ $redis_password | b64enc | quote }}

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-celery-backend-uri
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ printf "redis://:%s@%s-redis:6379/0" $redis_password .Release.Name | b64enc | quote }}
