################################
## Airflow Secrets
#################################
{{- if not .Values.fernetKeySecretName }}
{{ $generated_fernet_key := (randAlphaNum 32 | b64enc) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fernet-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  fernet-key: {{ (default $generated_fernet_key .Values.fernetKey) | b64enc | quote }}
{{- end }}
---
# If both of these secret names are not set, we will either use the set password, or generate one
{{- if not (and .Values.redis.passwordSecretName .Values.redis.brokerURLSecretName) }}
{{ $random_redis_password := randAlphaNum 10 }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-redis-password
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ (default $random_redis_password .Values.redis.password) | b64enc | quote }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-broker-url
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "redis://:%s@%s-redis:6379/0" (default $random_redis_password .Values.redis.password) .Release.Name) | b64enc | quote }}
{{- end }}
---
{{- if (and .Values.data.metadataConnection (not .Values.data.metadataSecretName)) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-metadata
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "postgresql://%s:%s@%s:%s/%s" .Values.data.metadataConnection.user .Values.data.metadataConnection.pass (ternary (printf "%s-%s" .Release.Name "pgbouncer") .Values.data.metadataConnection.host .Values.pgbouncer.enabled) ((ternary .Values.ports.pgbouncer .Values.data.metadataConnection.port .Values.pgbouncer.enabled) | toString) (ternary .Release.Name .Values.data.metadataConnection.db .Values.pgbouncer.enabled)) | b64enc | quote }}
{{- end }}
---
{{- if (and .Values.data.resultBackendConnection (not .Values.data.resultBackendSecretName)) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-airflow-result-backend
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "db+postgresql://%s:%s@%s:%s/%s" .Values.data.resultBackendConnection.user .Values.data.resultBackendConnection.pass (ternary (printf "%s-%s" .Release.Name "pgbouncer") .Values.data.resultBackendConnection.host .Values.pgbouncer.enabled) ((ternary .Values.ports.pgbouncer .Values.data.resultBackendConnection.port .Values.pgbouncer.enabled) | toString) (ternary .Release.Name .Values.data.resultBackendConnection.db .Values.pgbouncer.enabled)) | b64enc | quote }}
{{- end }}
