################################
## Fluentd ClusterRoleBinding
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    tier: logging
    component: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.fullname" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fluentd.fullname" . }}
  apiGroup: ""
{{- end -}}
