# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
images:
  nginxIngress: astronomerinc/ap-nginx:0.1.4
  defaultBackend: astronomerinc/ap-default-backend:0.1.4

## Dependent on cloud provider
preserveSourceIP: false

proxyConnectTimeout: 15
proxyReadTimeout: 600
proxySendTimeout: 600
proxyBodySize: "512m"
hstsIncludeSubdomains: false
serverNameHashBucketSize: 256
