# Default values for kube-state.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageTag: v1.4.0

images:
  kubestate:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.4.0

env: {}
resources: {}
# limits:
#  cpu: 100m
#  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

ports:
  scrape: 8080
  telemetry: 8081
