pipeline:
  # Just build when we push to master
  build:
    image: astronomerio/ap-build:0.0.5
    commands:
      - make build
    when:
      event: push
      branch: master

  # Build when we tag
  build:
    image: astronomerio/ap-build:0.0.5
    commands:
      - make build
    environment:
      - ASTRONOMER_VERSION=${DRONE_TAG##v}
    when:
      event: tag
      branch: [ master, release-* ]

  # Push to helm.astronomer.io
  push:
    image: astronomerio/ap-build:0.0.5
    commands:
      - echo $${GCP_TOKEN}
      - echo "========================="
      - printf "%s" $${GCP_TOKEN}
      # - printf "%s\n" $${GCP_TOKEN} > /tmp/gcs_token.json
      # - cat /tmp/gcs_token.json
      # - gcloud auth activate-service-account --key-file=/tmp/gcs_token.json
      # - make push-repo
    environment:
      - ASTRONOMER_VERSION=${DRONE_TAG##v}
      # - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcs_token.json
    secrets: [ gcp_token ]
    when:
      event: push
      branch: master
    # when:
    #   event: tag
    #   branch: [ master, release-* ]

  # Push new versions back to github
  # commit:
  #   image: appleboy/drone-git-push
  #   remote_name: origin
  #   branch: master
  #   commit: true
  #   commit_message: "Bump to version ${DRONE_TAG##v}"
  #   key: $${GIT_PUSH_SSH_KEY}
  #   when:
  #     event: tag
  #     branch: [ master, release-* ]
