pipeline:
  ##################################
  ## Github pushes - build with SHA
  ###################################
  build:
    image: astronomerio/ap-build:0.0.7
    environment:
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - ASTRONOMER_VERSION=0.0.0
    commands:
      - echo $ASTRONOMER_VERSION
      - make build
    when:
      event: push
      branch: [ master, release-* ]

  ##################################
  ## Deployment
  ###################################
  build:
    image: astronomerio/ap-build:0.0.7
    environment:
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    commands:
      - make build
    when:
      event: deployment
      branch: [ master, release-* ]
      environment: production

  # Push to helm.astronomer.io
  push:
    image: astronomerio/ap-build:0.0.7
    environment:
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    commands:
      - printf "%s" $${GCP_TOKEN} > /tmp/gcs_token.json
      - sed -i 's/BEGINPRIVATEKEY/BEGIN PRIVATE KEY/g' /tmp/gcs_token.json
      - sed -i 's/ENDPRIVATEKEY/END PRIVATE KEY/g' /tmp/gcs_token.json
      - gcloud auth activate-service-account --key-file=/tmp/gcs_token.json
      - make push-repo
    secrets: [ gcp_token ]
    when:
      event: deployment
      branch: [ master, release-* ]
      environment: production

  # Push new versions back to github
  commit-push-tags:
    image: astronomerio/ap-build:0.0.7
    commands:
      - mkdir -p /root/.ssh
      - echo "$${GIT_PUSH_SSH_KEY}" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H github.com >> /root/.ssh/known_hosts
      - git remote set-url origin git@github.com:${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}.git
      - git config --global user.name "schnie"
      - git config --global user.email "schnie@astronomer.io"
      - git add .
      - git commit -m "[skip ci] Bump to $${ASTRONOMER_VERSION}"
      - git push -u origin ${DRONE_COMMIT_BRANCH}
    secrets: [ git_push_ssh_key ]
    when:
      event: deployment
      branch: [ master, release-* ]
      environment: production
