pipeline:
  # Just build when we push to master
  build:
    image: astronomerio/ap-build:0.0.4
    commands:
      - make build
    # environment:
    #   - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
    when:
      event: push
      branch: master

  # Push to helm.astronomer.io
  push:
    image: astronomerio/ap-build:0.0.4
    commands:
      - make push
    environment:
      - ASTRONOMER_VERSION=${DRONE_TAG##v}
    when:
      event: tag
      branch: [ master, release-* ]
