pipeline:
  # Just build when we push to master
  build:
    image: astronomerio/ap-build:0.0.5
    commands:
      - make build
    # environment:
    #   - ASTRONOMER_VERSION=${DRONE_COMMIT_SHA:0:8}
    when:
      event: push
      branch: master

  # Push to helm.astronomer.io
  push:
    image: astronomerio/ap-build:0.0.5
    commands:
      - echo ${GCP_TOKEN} >> /tmp/gcs_token.json
      - make push-repo
    environment:
      - ASTRONOMER_VERSION=${DRONE_TAG##v}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcs_token.json
    when:
      event: tag
      branch: [ master, release-* ]

  commit:
    image: appleboy/drone-git-push
    remote_name: origin
    branch: master
    commit: true
    commit_message: "Bump to version ${DRONE_TAG##v}"
    key: $${GIT_PUSH_SSH_KEY}
    when:
      event: tag
      branch: [ master, release-* ]
