#################################
## Chart overrides
#################################

# Global overrides
global:
  loadBalancerIP:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  baseDomain:
  tlsSecret:
  acme: false

# Airflow config overrides
airflow:
  env:
  secret:
