################################
## Chart overrides
#################################

# Global overrides
global:
  loadBalancerIP:
  baseDomain:
  acme: false
  tlsSecret:
  nginxAuthSecret:
  registryAuthSecret:


# Airflow overrides
airflow:
  # Worker settings
  workers:
    persistence:
      enabled: true

  # Database connections
  data:
    airflowMetadataSecret:
    airflowResultBackendSecret:
    airflowBrokerSecret:
    grafanaBackendSecret:
