#################################
## Chart overrides
#################################

# Global overrides
global:
  loadBalancerIP:
  baseDomain:
  tlsSecret:
  acme: false

# Airflow config overrides
airflow:
  env:
  secret:
