################################
## Chart overrides
#################################

# Global overrides
global:
  loadBalancerIP:
  baseDomain:
  acme: false
  tlsSecret: "astronomer-tls"
  nginxAuthSecret: "nginx-auth"
  registryAuthSecret:


# Airflow overrides
airflow:
  # Worker settings
  workers:
    persistence:
      enabled: true

  # Database connections
  data:
    airflowMetadataSecret: "airflow-metadata"
    airflowResultBackendSecret: "airflow-result-backend"
    airflowBrokerSecret: "airflow-broker"
    grafanaBackendSecret: "grafana-backend"
