dependencies:
  # Platform components
  - name: astronomer
    condition: astronomer.enabled
  - name: nginx
    condition: nginx.enabled
  - name: grafana
    condition: grafana.enabled
  - name: prometheus
    condition: prometheus.enabled

  # Airflow chart is deployed by the platform
  - name: airflow
    condition: airflow.enabled
