dependencies:
  - name: astronomer
    version: 0.0.0
    condition: global.modules.astronomer.enabled
  - name: airflow
    version: 0.0.0
    condition: global.modules.airflow.enabled
  - name: clickstream
    version: 0.0.0
    condition: global.modules.clickstream.enabled
  - name: nginx
    version: 0.0.0
    condition: global.modules.nginx.enabled
