dependencies:
  - name: astronomer
    condition: global.modules.astronomer.enabled
  - name: airflow
    condition: global.modules.airflow.enabled
  - name: nginx
    condition: global.baseDomain
  - name: grafana
    condition: global.modules.grafana.enabled
  - name: prometheus
    condition: global.modules.prometheus.enabled
  - name: elasticsearch
    condition: global.modules.elasticsearch.enabled
