################################
## Astronomer global variables
#################################
global:
  # Kubernetes namespace to install into
  namespace: astronomer

  # If RBAC on cluster is enabled
  rbacEnabled: true

  # Base domain for all subdomains exposed through ingress
  baseDomain:

  # Temporary until full PCE install available
  organization:


################################
## Astronomer modules
#################################
modules:
  pilot:
    enabled: true
  airflow:
    enabled: true
  clickstream:
    enabled: false


################################
## Astronomer Pilot Chart
#################################
pilot:
  # User in pilot containers
  uid: 100

  # Images for pilot
  images:
    commander: astronomerinc/ap-pce-commander:0.0.8
    phoenix: astronomerinc/ap-pce-phoenix:0.0.8

  # Static IP name for pilot
  staticIpName:

  # Secret for generating JWTs
  jwtSecret:

  ingress:
    acme: false


################################
## Astronomer Airflow Chart
#################################
airflow:
  # Used in labels
  appName: airflow

  # User and group of airflow user
  uid: 100
  gid: 101

  ingress:
    acme: false

  # Astronomer Airflow images
  images:
    airflow: astronomerinc/ap-airflow:0.0.17
    statsdExporter: astronomerinc/ap-statsd-exporter:0.0.17
    prometheus: astronomerinc/ap-prometheus:0.0.17
    grafana: astronomerinc/ap-grafana:0.0.17

  # Static IP name for airflow
  staticIpName:

  # Airflow worker settings
  workers:
    # Number of airflow celery workers in StatefulSet
    replicas: 3

    persistence:
      # Enable persistent volumes
      enabled: false

      # Volume size for worker StatefulSet
      size: 10Gi

    # Grace period for tasks to finish after SIGTERM is sent from kubernetes
    terminationGracePeriodSeconds: 600

  # Environment variables for all airflow containers
  env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: "CeleryExecutor"
    - name: AIRFLOW__SCHEDULER__STATSD_ON
      value: "True"
    - name: AIRFLOW__SCHEDULER__STATSD_PORT
      value: "9125"
    - name: AIRFLOW__SCHEDULER__STATSD_PREFIX
      value: "airflow"
    - name: ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION
      value: "15"

  # Astronomer Airflow database config
  data:

    # Main Airflow database
    metadata:
      host:
      port:
      database:
      username:
      password:

    # Celery results backend
    results:
      host:
      port:
      database:
      username:
      password:

    # Celery broker
    broker:
      host:
      port:
      database:
      username:
      password:

    # Grafana backend
    grafana:
      host:
      port:
      database:
      username:
      password:
