#################################
## Astronomer global configuration
#################################
global:
  # Base domain for all subdomains exposed through ingress
  baseDomain:

  # Use kube-lego
  acme: false

  # If RBAC on cluster is enabled
  rbacEnabled: true

  # Name of secret containing TLS certificate
  tlsSecret:

  # Name of secret containing basic auth for NGINX
  nginxAuthSecret: "nginx-auth"

  # Name of secret containing docker registry auth
  registryAuthSecret: "registry-auth"

  helmRepo: "https://helm.astronomer.io"

  # Astronomer modules
  modules:

    # Enable astronomer module
    astronomer:
      enabled: true

    # Enable airflow module
    airflow:
      enabled: false

    # Enable clickstream module
    clickstream:
      enabled: false

    # Enable NGINX ingress module
    nginx:
      enabled: true

#################################
## Nginx configuration
#################################
nginx:
  # IP address the nginx ingress should bind to
  loadBalancerIP:

  # Used to restrict IPs which can reach the nginx ingress
  loadBalancerSourceRanges:

#################################
## Airflow configuration
#################################
airflow:
  # Worker settings
  workers:
    # Enable persistence to keep logs around between deploys
    persistence:
      enabled: true
      # If using a custom storageClass, pass name ref to all statefulSets here
      storageClassName:

#################################
## Registry configuration
#################################
registry:
  # Enable persistence to keep registry data between deploys
  persistence:
    enabled: true
    size: 50Gi

  data:
    deployNamespace: astronomer
