################################
## Astronomer global variables
#################################
global:
  # If RBAC on cluster is enabled
  rbacEnabled: true

  # Base domain for all subdomains exposed through ingress
  baseDomain:

  # Astronomer modules
  modules:
    astronomer:
      enabled: true
    airflow:
      enabled: true
    clickstream:
      enabled: false
