################################
## Astronomer global variables
#################################
global:
  # Kubernetes namespace to install into
  namespace: astronomer

  # If RBAC on cluster is enabled
  rbacEnabled: true

  # Base domain for all subdomains exposed through ingress
  baseDomain:

  # Temporary until full PCE install available
  organization:


################################
## Astronomer modules
#################################
modules:
  pilot:
    enabled: true
  airflow:
    enabled: true
  clickstream:
    enabled: false
