################################
## Astronomer global variables
#################################
global:
  # Base domain for all subdomains exposed through ingress
  baseDomain:

  # Use kube-lego
  acme: false

  # If RBAC on cluster is enabled
  rbacEnabled: true

  # Astronomer modules
  modules:
    astronomer:
      enabled: true
    airflow:
      enabled: true
    clickstream:
      enabled: false
    nginx:
      enabled: true
