################################
## Astronomer Commander RoleBinding
#################################
{{- if .Values.global.rbacEnabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-commander
  namespace: {{ .Values.global.namespace }}
  labels:
    tier: astronomer-pilot
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-commander
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-commander
    namespace: {{ .Values.global.namespace }}
{{- end }}
