################################
## Airflow Prometheus Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    tier: airflow-monitoring
    component: prometheus
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow-monitoring
      component: prometheus
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: airflow-monitoring
        component: prometheus
        release: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ .Files.Get "prometheus-configmap.yaml" | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-prometheus
          image: {{ .Values.images.prometheus }}
          args:
            - "--config.file=/etc/prometheus/config/kubernetes.yaml"
            - "--storage.tsdb.path=/prometheus"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/config
          ports:
            - name: prometheus-data
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /graph
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /graph
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: {{ .Release.Name }}-prometheus
            items:
              - key: kubernetes.yaml
                path: kubernetes.yaml
