################################
## Airflow Prometheus Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: prometheus
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    component: prometheus
    release: {{ .Release.Name }}
  ports:
    - name: prometheus-data
      protocol: TCP
      port: 9090
      targetPort: 9090
