################################
## Airflow Prometheus ConfigMap
#################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: prometheus
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
data:
  kubernetes.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 30s

    scrape_configs:
      - job_name: 'airflow_scheduler'
        static_configs:
          - targets: ["{{ .Release.Name }}-statsd:9102"]
