################################
## Airflow Prometheus Service Account
#################################
{{- if .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
