{{ define "grafana_image" -}}
{{ .Values.images.grafana.repository }}:{{ .Values.images.grafana.tag }}
{{- end }}

{{ define "grafana_url" -}}
grafana.{{ .Values.global.baseDomain }}
{{- end }}

{{ define "db_bootstrapper_image" -}}
{{ .Values.images.dbBootstrapper.repository }}:{{ .Values.images.dbBootstrapper.tag }}
{{- end }}
