################################
## Grafana Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: "{{ .Release.Name }}-grafana"
  labels:
    tier: monitoring
    component: grafana
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: monitoring
      component: grafana
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
  template:
    metadata:
      labels:
        tier: monitoring
        component: grafana
        release: {{ .Release.Name }}
        workspace: {{ .Values.workspace }}
    spec:
      restartPolicy: Always
      {{- if not .Values.backendSecretName }}
      serviceAccountName: {{ template "bootstrapper_service_account" . }}
      initContainers:
        - name: "{{ .Release.Name }}-grafana-bootstrapper"
          image: {{ template "db_bootstrapper_image" . }}
          imagePullPolicy: {{ .Values.images.dbBootstrapper.pullPolicy }}
          env:
            - name: BOOTSTRAP_DB
              valueFrom:
                secretKeyRef:
                  name: astronomer-bootstrap
                  key: connection
            - name: DB_NAME
              value: {{ .Release.Name }}-grafana
            - name: SECRET_NAME
              value: {{ template "backend_secret" . }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: IN_CLUSTER
              value: "true"
      {{- end }}
      containers:
        - name: "{{ .Release.Name }}-grafana"
          image: {{ template "grafana_image" . }}
          imagePullPolicy: {{ .Values.images.grafana.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: grafana-ui
              containerPort: {{ .Values.ports.http }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.ports.http }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.ports.http }}
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: grafana-datasource-volume
              mountPath: /etc/grafana/provisioning/datasources
          env:
            - name: GF_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "backend_secret" . }}
                  key: connection
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
      volumes:
        - name: grafana-datasource-volume
          configMap:
            name: "{{ .Release.Name }}-grafana-datasource"
            items:
              - key: datasource.yaml
                path: datasource.yaml
