################################
## Airflow Grafana Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    tier: monitoring
    component: grafana
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: monitoring
    component: grafana
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
  ports:
    - name: grafana-ui
      protocol: TCP
      port: 3000
      targetPort: 3000
