################################
## Grafana ConfigMap
#################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "grafana.fullname" . }}-datasource
  labels:
    tier: monitoring
    component: grafana
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  datasource.yaml: |-
    datasources:
      - name: Prometheus
        type: prometheus
        org_id: 1
        url: "http://{{ .Release.Name }}-prometheus:9090"
        access: proxy
        is_default: true
