################################
## Grafana Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    tier: monitoring
    component: grafana
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: monitoring
      component: grafana
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
  template:
    metadata:
      labels:
        tier: monitoring
        component: grafana
        release: {{ .Release.Name }}
        workspace: {{ .Values.workspace }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-grafana
          image: {{ .Values.image }}
          ports:
            - name: grafana-ui
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: GF_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafanaBackendSecret }}
                  key: connection
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: ASTRO_DEFAULT_PROMETHEUS_HOST
              value: "http://{{ .Release.Name }}-prometheus:9090"
