################################
## Grafana NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "grafana.fullname" . }}-policy
  labels:
    tier: monitoring
    component: grafana-policy
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: monitoring
      component: grafana
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.http }}
