##############################################
## Airflow Kube-State Deployment
##############################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ template "kube-state.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "kube-state.name" . }}
    component: kube-state
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ template "kube-state.name" . }}
      component: kube-state
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "kube-state.name" . }}
        component: kube-state
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "kube-state.fullname" . }}
      containers:
      - name: {{ template "kube-state.fullname" . }}
        image: {{- include "kube-state.image" . | indent 1 }}
        ports:
        - name: scrape
          containerPort: {{ .Values.ports.scrape }}
        - name: telemetry
          containerPort: {{ .Values.ports.telemetry }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ports.scrape }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
      - name: addon-resizer
        image: k8s.gcr.io/addon-resizer:1.7
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container={{ template "kube-state.fullname" . }}
          - --cpu=100m
          - --extra-cpu=1m
          - --memory=100Mi
          - --extra-memory=2Mi
          - --threshold=5
          - --deployment={{ template "kube-state.fullname" . }}
