################################
## Kube State Service Acount
#################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-state.fullname" . }}
  namespace: {{ .Release.Namespace }}
