################################
## Airflow configuration
#################################
#
# Astronomer Airflow images
images:
  airflow:
    name: astronomerinc/ap-airflow
    tag: "0.3.0-rc.6"  # TODO: remove this temporary workaround with final release
  statsd:
    name: astronomerinc/ap-statsd-exporter
    tag: "0.3.0-rc.6"  # TODO: remove this temporary workaround with final release
  redis:
    name:  astronomerinc/ap-redis
    tag: "0.3.0-rc.6"  # TODO: remove this temporary workaround with final release

# Astronomer Airflow database config
data:
  airflowMetadataSecret: "airflow-metadata"
  airflowResultBackendSecret: "airflow-result-backend"
  airflowBrokerSecret: "airflow-broker"
