################################
## Airflow StatsD NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-statsd-policy
  labels:
    tier: airflow
    component: statsd-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: statsd
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          tier: monitoring
          component: prometheus
    ports:
    - protocol: UDP
      port: {{ .Values.ports.statsdIngest }}
    - protocol: TCP
      port: {{ .Values.ports.statsdScrape }}
