################################
## Airflow Webserver Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
  ports:
    - name: airflow-ui
      protocol: TCP
      port: {{ .Values.ports.airflowUI }}
      targetPort: {{ .Values.ports.airflowUI }}
