################################
## Airflow Webserver NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-webserver-policy
  labels:
    tier: airflow-networking
    component: airflow-webserver-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: webserver
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8080
