################################
## Airflow Webserver Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
spec:
  type: NodePort
  selector:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
  ports:
    - name: webserver-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
