################################
## Airflow Webserver Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: webserver
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
  template:
    metadata:
      labels:
        tier: airflow
        component: webserver
        release: {{ .Release.Name }}
        workspace: {{ .Values.workspace }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.uid }}
      {{- if .Values.global.registryAuthSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registryAuthSecret }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-webserver
          image: {{- include "airflow_image" . | indent 1 }}
          args: ["airflow", "webserver"]
          ports:
            - name: webserver-ui
              containerPort: {{ .Values.ports.airflowUI }}
          livenessProbe:
            httpGet:
              path: /admin/
              port: {{ .Values.ports.airflowUI }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/
              port: {{ .Values.ports.airflowUI }}
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          {{- include "airflow_environment" . | indent 10 }}
