################################
## Astronomer Houston Secrets
#################################

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-jwt-passphrase
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-encryption-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
{{ if .Values.auth.google.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-google-client-secret
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  client_id: {{ .Values.auth.google.client_secret | b64enc }}
{{ end }}