################################
## Astronomer Houston Secrets
#################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-jwt-passphrase
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-encryption-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
{{ if .Values.smtp.uri }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-smtp-uri
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ .Values.smtp.uri | b64enc }}
{{ end }}
