################################
## Astronomer Houston Secrets
#################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-jwt-passphrase
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-encryption-key
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "random_string" . }}

---
{{ if .Values.auth.google.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-google-client-secret
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  clientSecret: {{ .Values.auth.google.clientSecret | b64enc }}
{{ end }}

---
{{ if .Values.data.houstonSMTPSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.data.houstonSMTPSecret }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ .Values.smtp.uri }}
{{ end }}