################################
## Astronomer Houston Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-houston
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: houston
      tier: astronomer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: houston
        tier: astronomer
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.uid }}
      containers:
        - name: {{ .Release.Name }}-houston
          image: {{ .Values.images.houston }}
          ports:
            - name: houston-http
              containerPort: 8870
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8870
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8870
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          {{- include "houston_environment" . | indent 10 }}