# Default values for Prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  init:
    repository: astronomerinc/ap-base
    tag: 0.6.2
    pullPolicy: IfNotPresent
  prometheus:
    repository: astronomerinc/ap-prometheus
    tag: 0.6.2
    pullPolicy: IfNotPresent

resources: {}
#  limits:
#   cpu: 100m
#   memory: 128Mi
#  requests:
#   cpu: 100m
#   memory: 128Mi

# Which directory prometheus data should be stored
dataDir: "/prometheus"

# How long prometheus should keep data before removing
retention: 15d

# Enable persistence for Prometheus
persistence:
  enabled: true
  size: 100Gi
  # If using a custom storageClass, pass name ref to all statefulSets here
  storageClassName:

ports:
  http: 9090
