# Default values for Prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  prometheus:
    name: astronomerinc/ap-prometheus
    tag: 0.3.1

dataDir: "/prometheus"

# Enable persistence for Prometheus
persistence:
  enabled: true
  size: 50Gi
  # If using a custom storageClass, pass name ref to all statefulSets here
  storageClassName:

workspace: default

port: 9090
