# Default values for Prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  prometheus: astronomerinc/ap-prometheus

imageTag: 0.2.0

dataDir: "/prometheus"

# Enable persistence for Prometheus
persistence:
  enabled: true
  size: 50Gi

workspace: default
