apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: kube-state-metrics-resizer
rules:
  - apiGroups: [""]
    resources:
      - pods
      verbs: ["get"]
  - apiGroups: ["extensions"]
    resources:
      - deployments
    resourceNames: ["kube-state"]
    verbs: ["get", "update"]
