################################
## NGINX Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    tier: nginx
    component: ingress-controller
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    # AWS annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.loadBalancerSourceRanges }}
  {{- end }}
  {{- if .Values.preserveSourceIP }}
  externalTrafficPolicy: "Cluster"
  {{- end }}
  selector:
    tier: nginx
    component: ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.ports.https }}
      targetPort: {{ .Values.ports.https }}
      protocol: TCP
      name: https
