################################
## NGINX Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    tier: nginx
    component: ingress-controller
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  {{- if .Values.global.ingress.loadBalancerIP }}
  loadBalancerIP: {{ .Values.global.ingress.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: "Local"
  selector:
    tier: nginx
    component: ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
