################################
## Airflow Prometheus Service Account
#################################
{{- if .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    tier: monitoring
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- end }}
