################################
## Prometheus ClusterRole
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "nodes/proxy"
      - "services"
      - "endpoints"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
{{- end }}
