################################
## Prometheus NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-prometheus-policy
  labels:
    tier: monitoring
    component: airflow-prometheus-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: prometheus
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: monitoring
          component: grafana
          release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: {{ .Values.port }}
