################################
## Prometheus Cluster Role Binding
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
