################################
## Prometheus Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-prometheus"
  labels:
    tier: monitoring
    component: prometheus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: monitoring
    component: prometheus
    release: {{ .Release.Name }}
  ports:
    - name: prometheus-data
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
