################################
## Astronomer Registry Secrets
#################################
{{ if and .Values.global.baseDomain (not .Values.registry.auth.secretName) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "registry_auth_secret" . }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.registry.auth.connection }}
  .dockerconfigjson: {{ .Values.registry.auth.connection }}
  {{- else }}
  .dockerconfigjson: {{ include "registry_docker_config" . | b64enc }}
  {{- end }}
{{- end }}
