################################
## Astronomer Houston Secrets
#################################

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-registry-auth
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "registry_docker_config" . | b64enc }}
