#################################
### Astronomer Registry Deployment
##################################
#kind: Deployment
#apiVersion: apps/v1beta2
#metadata:
#  name: {{ .Release.Name }}-registry
#  namespace: {{ .Values.global.namespace }}
#  labels:
#    component: registry
#    tier: astronomer-pilot
#    release: {{ .Release.Name }}
#    chart: {{ .Chart.Name }}
#    heritage: {{ .Release.Service }}
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      component: registry
#      tier: astronomer-pilot
#      release: {{ .Release.Name }}
#  template:
#    metadata:
#      labels:
#        component: registry
#        tier: astronomer-pilot
#        release: {{ .Release.Name }}
#    spec:
#      serviceAccountName: {{ .Release.Name }}-registry
#      restartPolicy: Always
#      securityContext:
#        runAsUser: {{ .Values.uid }}
#      containers:
#        - name: {{ .Release.Name }}-registry
#          image: {{ .Values.images.registry }}
#          ports:
#            - name: registry-http
#              containerPort: 5000
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 5000
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 5000
#            initialDelaySeconds: 10
#            periodSeconds: 10
