################################
## Airflow Flower Service Component
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-flower
  labels:
    tier: airflow
    component: flower
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: airflow
    component: flower
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
  ports:
    - name: flower-ui
      protocol: TCP
      port: 5555
      targetPort: 5555
