################################
## Airflow Flower Service Component
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-flower
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: flower
    tier: airflow-core
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    component: flower
    release: {{ .Release.Name }}
  ports:
    - name: flower-ui
      protocol: TCP
      port: 5555
      targetPort: 5555
