{{ define "helm_globals" -}}
{{ print "{" -}}
{{ printf "\"baseDomain\":\"%v\"," .Values.global.baseDomain -}}
{{ printf "\"registryAuthSecret\":\"%v\"," .Values.global.registryAuthSecret -}}
{{ printf "\"acme\":%v," (print .Values.global.acme | toString) -}}
{{ printf "\"rbacEnabled\":%v," (print .Values.global.rbacEnabled | toString) -}}
{{ printf "\"tlsSecret\":\"%v\"" (print .Values.global.tlsSecret | toString | replace "<nil>" "") -}}
{{ print "}" -}}
{{- end }}

{{- define "random_string" }}
  {{- randAlphaNum 32 | b64enc }}
{{- end }}

{{ define "auth_strategies" -}}
  {{- if or .Values.auth.local.enabled -}}
    local,
  {{- end -}}
  {{- if or .Values.auth.google.enabled -}}
    google_oauth,
  {{- end -}}
{{- end }}