{{/* Airflow environment variables */}}
{{- define "houston_environment" }}
  # Houston Envs
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8870"
  - name: API_ENDPOINT_URL
    value: "/v1"
  - name: WEBSOCKET_ENDPOINT_URL
    value: "/ws"
  - name: PLAYGROUND_ENDPOINT_URL
    value: "/playground"
  - name: DEBUG_DB
    value: "false"
  - name: AUTH_STRATEGY
    value: "local"
  - name: COMMANDER_HOST
    value: "http://{{ .Release.Name }}-commander"
  - name: COMMANDER_PORT
    value: "8880"
  # Secret Envs
  - name: JWT_PASSPHRASE
    valueFrom:
      secretKeyRef:
        name: {{ .Values.houstonJwtPassphraseSecret }}
        key: passphrase
  - name: POSTGRES_URI
    valueFrom:
      secretKeyRef:
        name: {{ .Values.houstonDatabaseSecret }}
        key: connection
{{- end }}
