################################
## Astronomer Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-astronomer-ingress
  labels:
    component: astronomer-ingress
    tier: astronomer
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
spec:
  tls:
    - secretName: {{ .Release.Name }}-astronomer-tls
      hosts:
        - registry.{{ .Values.global.baseDomain }}
        - phoenix.{{ .Values.global.baseDomain }}
  rules:
  - host: registry.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-registry
            servicePort: registry-http
  - host: phoenix.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /deployments/patch/
          backend:
            serviceName: {{ .Release.Name }}-phoenix
            servicePort: phoenix-http
{{- end }}
