################################
## Grafana Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  labels:
    tier: grafana-networking
    component: grafana-ingress
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: {{ eq .Values.global.acme true | quote }}
spec:
  {{- if or .Values.global.tlsSecret .Values.global.acme }}
  tls:
  {{- if .Values.global.acme }}
    - secretName: grafana-tls
  {{- end }}
  {{- if .Values.global.tlsSecret }}
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - {{- include "grafana_url" . | indent 1 }}
  {{- end }}
  rules:
    - host: {{- include "grafana_url" . | indent 1 }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-grafana
              servicePort: grafana-ui
{{- end }}
