# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User and group of airflow user
uid: 100
gid: 101

# Astronomer Airflow images
images:
  airflow:
    name: astronomerinc/ap-airflow
    tag: 0.3.1
  statsd:
    name: astronomerinc/ap-statsd-exporter
    tag: 0.3.1
  redis:
    name:  astronomerinc/ap-redis
    tag: 0.3.1

# Enable platform authentication
auth:
  enabled: true

# Airflow Worker Config
workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

  persistence:
    # Enable persistent volumes
    enabled: true
    # Volume size for worker StatefulSet
    size: 10Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:

  # Grace period for tasks to finish after SIGTERM is sent from kubernetes
  terminationGracePeriodSeconds: 600

# Airflow scheduler settings
scheduler:

  podDisruptionBudget:

    # Ensure we have one replica always running
    maxUnavailable: 1

# Environment variables for all airflow containers
env:

# Astronomer Airflow database config
data:
  airflowMetadataSecret: airflow-metadata
  airflowResultBackendSecret: airflow-result-backend
  # airflowBrokerSecret: airflow-broker

redis:
  terminationGracePeriodSeconds: 600

  persistence:
    # Enable persistent volumes
    enabled: true
    # Volume size for worker StatefulSet
    size: 1Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:

ports:
  flowerUI: 5555
  airflowUI: 8080
  workerLogs: 8793
  redisDB: 6379
  statsdIngest: 9125
  statsdScrape: 9102
