# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User and group of airflow user
uid: 100
gid: 101

ingress:
  acme: true

# Astronomer Airflow images
images:
  airflow: astronomerinc/ap-airflow:0.0.27
  statsdExporter: astronomerinc/ap-statsd-exporter:0.0.27
  prometheus: astronomerinc/ap-prometheus:0.0.27
  grafana: astronomerinc/ap-grafana:0.0.27

# Static IP name for airflow
staticIpName:

# Airflow worker settings
workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

  persistence:
    # Enable persistent volumes
    enabled: false

    # Volume size for worker StatefulSet
    size: 10Gi

  # Grace period for tasks to finish after SIGTERM is sent from kubernetes
  terminationGracePeriodSeconds: 600

# Environment variables for all airflow containers
env:
  - name: AIRFLOW__CORE__EXECUTOR
    value: "CeleryExecutor"
  - name: AIRFLOW__SCHEDULER__STATSD_ON
    value: "True"
  - name: AIRFLOW__SCHEDULER__STATSD_PORT
    value: "9125"
  - name: AIRFLOW__SCHEDULER__STATSD_PREFIX
    value: "airflow"
  - name: ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION
    value: "15"

# Astronomer Airflow database config
data:

  # Main Airflow database
  metadata:
    host:
    port:
    database:
    username:
    password:

  # Celery results backend
  results:
    host:
    port:
    database:
    username:
    password:

  # Celery broker
  broker:
    host:
    port:
    database:
    username:
    password:

  # Grafana backend
  grafana:
    host:
    port:
    database:
    username:
    password:
