# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User and group of airflow user
uid: 100
gid: 101

# Astronomer Airflow images
images:
  airflow:
    name: astronomerinc/ap-airflow
    tag: 0.2.0
  statsd:
    name: astronomerinc/ap-statsd-exporter
    tag: 0.2.0
  prometheus:
    name: astronomerinc/ap-prometheus
    tag: 0.2.0
  grafana:
    name: astronomerinc/ap-grafana
    tag: 0.2.0

# Airflow Worker Config
workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

  persistence:
    # Enable persistent volumes
    enabled: false
    # Volume size for worker StatefulSet
    size: 10Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:

  # Grace period for tasks to finish after SIGTERM is sent from kubernetes
  terminationGracePeriodSeconds: 600

# Airflow scheduler settings
scheduler:

  podDisruptionBudget:

    # Ensure we have one replica always running
    maxUnavailable: 1

# Prometheus Configs
prometheus:
  dataDir: "/prometheus"

  # Enable persistence for Prometheus
  persistence:
    enabled: true
    size: 50Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:

# Environment variables for all airflow containers
env:

# Astronomer Airflow database config
data:
  airflowMetadataSecret: airflow-metadata
  airflowResultBackendSecret: airflow-result-backend
  airflowBrokerSecret: airflow-broker
