# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User and group of airflow user
uid: 100
gid: 101

# Astronomer Airflow images
images:
  airflow: astronomerinc/ap-airflow:0.4.0
  statsdExporter: astronomerinc/ap-statsd-exporter:0.4.0
  prometheus: astronomerinc/ap-prometheus:0.4.0
  grafana: astronomerinc/ap-grafana:0.4.0

# Airflow scheduler settings
scheduler:

  podDisruptionBudget:

    # Ensure we have one replica always running
    maxUnavailable: 1

# Prometheus Configs
prometheus:
  dataDir: "/prometheus"

  # Enable persistence for Prometheus
  persistence:
    enabled: true
    size: 50Gi

# Environment variables for all airflow containers
env:

# Astronomer Airflow database config
data:
  airflowMetadataSecret: "airflow-metadata"
  grafanaBackendSecret: "grafana-backend"
