################################
## Curator CronJob
#################################
{{- if .Values.curator.enabled }}
apiVersion: {{ template "curator.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "elasticsearch.fullname" . }}-curator
  labels:
    tier: logging
    component: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.curator.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: {{ template "curator.image" . }}
            imagePullPolicy: {{ .Values.images.curator.pullPolicy }}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "elasticsearch.fullname" . }}-curator-config
          restartPolicy: OnFailure
{{- end }}
