################################
## Airflow Grafana Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: grafana
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- include "extra_labels" . }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    component: grafana
    release: {{ .Release.Name }}
  ports:
    - name: grafana-ui
      protocol: TCP
      port: 3000
      targetPort: 3000
