################################
## Pilot Ingress
#################################
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-pilot-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: pilot-ingress
    tier: astronomer-pilot
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/tls-acme: {{ eq .Values.ingress.acme true | quote }}
  {{- if .Values.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIpName }}
  {{- end }}
spec:
  rules:
  - host: phoenix.{{ .Values.global.baseDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-phoenix
          servicePort: phoenix-http
{{- end }}
