################################
## Astronomer ServiceAccount
#################################
{{- if .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-commander
  labels:
    tier: astronomer
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
