################################
## Airflow Scheduler Role Binding
#################################
{{- if .Values.global.rbacEnabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-scheduler
  namespace: airflow-tasks
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-scheduler
    namespace: {{ .Release.Namespace }}
{{- end }}
