################################
## Pgbouncer PodDisruptionBudget
#################################
# Mimic scheduler pdb. Scheduler isn't too useful if it can't talk to postgres
{{- if .Values.pgbouncer.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{ .Release.Name }}-pgbouncer-pdb
  namespace: {{ include "namespace" . }}
  labels:
    tier: airflow
    component: pgbouncer
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      tier: airflow
      component: pgbouncer
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
{{ toYaml .Values.scheduler.podDisruptionBudget | indent 2 }}
{{- end }}
