################################
## Pgbouncer Secret
#################################
{{- if .Values.pgbouncer.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pgbouncer_config_secret" . }}
  namespace: {{ include "namespace" . }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  pgbouncer.ini: {{ include "pgbouncer_config" . | b64enc }}
  users.txt: {{ include "pgbouncer_users" . | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pgbouncer_stats_secret" . }}
  namespace: {{ include "namespace" . }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  connection: {{ (printf "postgresql://%s:%s@localhost:%s/pgbouncer?sslmode=disable" .Values.data.metadataConnection.user .Values.data.metadataConnection.pass (.Values.ports.pgbouncer | toString)) | b64enc | quote }}
{{- end }}
