# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

# Images for pilot
images:
  commander:
    name: astronomerinc/ap-commander
    tag: 0.3.2
  registry:
    name: astronomerinc/ap-registry
    tag: 0.3.2
  houston:
    name: astronomerinc/ap-houston-api
    tag: 0.3.2
  orbit:
    name: astronomerinc/ap-orbit-ui
    tag: 0.3.2
  bootstrapper:
    name: astronomerinc/ap-db-bootstrapper
    tag: 0.3.2

# Astronomer platform config
data:
  houstonDatabaseSecret: "houston-database"
  airflowDatabaseSecret: "houston-database"

bootstrapDatabase: true

auth:
  local:
    enabled: true
  google:
    enabled: false
    clientId: ~
    clientSecret: ~

houston:
  env:

commander:
  env:

registry:
  # Enable persistence to keep registry data between deploys
  persistence:
    enabled: true
    size: 50Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:
  auth:
    service: "docker-registry"
    issuer: "houston"

ports:
  houstonHTTP: 8870
  commanderHTTP: 8880
  commanderGRPC: 50051
  orbitHTTP: 8080
  registryHTTP: 5000
