# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

# Images for pilot
images:
  commander: astronomerinc/ap-commander:0.0.27
  phoenix: astronomerinc/ap-phoenix:0.0.27
  registry: astronomerinc/ap-registry:0.0.27

# Static IP name for pilot
staticIpName:

# Secret for generating JWTs
jwtSecret:

ingress:
  acme: false

registry:
  username: admin
  password: admin
