# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

# Images for pilot
images:
  commander: astronomerinc/ap-commander
  registry: astronomerinc/ap-registry
  houston: astronomerinc/ap-houston-api
  orbit: astronomerinc/ap-orbit-ui

imageTag: 0.2.0

# Astronomer platform config
data:
  houstonDatabaseSecret: "houston-database"
  airflowDatabaseSecret: "houston-database"
  airflowRedisSecret: "airflow-redis"

registry:
  # Enable persistence to keep registry data between deploys
  persistence:
    enabled: true
    size: 50Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName:
auth:
  local:
    enabled: true
  google:
    enabled: false
    clientId: ~
    clientSecret: ~
  registry:
    issuer: houston
    expireDays: 3650

