# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# User in pilot containers
uid: 100

# Images for pilot
images:
  commander: astronomerinc/ap-commander:0.1.4
  registry: astronomerinc/ap-registry:0.1.4
  houston: astronomerinc/ap-houston-api:0.1.4

# Astronomer houston config
data:
  houstonJwtPassphraseSecret: "houston-jwt-passphrase"
  houstonDatabaseSecret: "houston-database"
  airflowDatabaseSecret: "airflow-database"
  airflowRedisSecret: "airflow-redis"


# Enable persistence to keep registry data between deploys
persistence:
  enabled: true
  size: 50Gi
