################################
## Worker Role Binding
#################################
{{- if and .Values.global.rbacEnabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-worker-rolebinding
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-worker-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-worker-serviceaccount
    namespace: {{ .Release.Namespace }}
{{- end }}
