################################
## Worker ServiceAccount
#################################
{{- if and .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-worker-serviceaccount
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- end }}
