################################
## Airflow Worker Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ include "namespace" . }}
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
  ports:
    - name: worker-logs
      port: {{ .Values.ports.workerLogs }}
