################################
## Airflow Worker HorizontalPodAutoscaler
#################################
{{- if .Values.workers.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-worker
  minReplicas: {{ .Values.workers.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workers.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.workers.autoscaling.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.workers.autoscaling.targetMemoryUtilization }}
{{- end }}
